version: '3.8'
services:
  app:
    build:
      context: ./dry-modas-vue-web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: ./dry-modas-spring-api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      URL_WEB: http://localhost:8080
      URL_API: http://localhost:5001
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      JWT_SECRET: 6777eb32e428b63738210ddfe846c5ce
      SECURITY_USER: teste
      SECURITY_PASSWORD: teste
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
